### ISSUE TITLE
Hidamari Flatpak shows up in Task Manager

### ISSUE THREAD

**Issue by notjl** [jeffshee/hidamari#105]
I am running KDE and Wayland and installed Hidamari through Flatpak and it works. My only gripe is that it shows up in the Task Manager.

![image](https://user-images.githubusercontent.com/58279268/236605993-7f391ba4-16f7-44c1-a11c-749644e6977a.png)

I tried forcing it to use Wayland through Flatseal and it shows me this
```py
Error: unable to open display 
Traceback (most recent call last):
  File "/app/bin/hidamari", line 44, in <module>
    sys.exit(main.main(VERSION, pkgdatadir, localedir))
  File "/app/share/hidamari/hidamari/__main__.py", line 43, in main
    sys_info.append(f"is_nvidia_proprietary = {is_nvidia_proprietary()}")
  File "/app/share/hidamari/hidamari/utils.py", line 44, in is_nvidia_proprietary
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'glxinfo -B' returned non-zero exit status 255.
```

**Comment by usbeehu** [comment]
Yup it's because the app doesn't have native wayland support and works through XWayland as a full screen window.
I also waiting for this to be solved, until that the extra Xorg icon will be there on the taskbar and that's it.
