### ISSUE TITLE
Hidamari doesn't open on Arch Linux

### ISSUE THREAD

**Issue by Azel04** [jeffshee/hidamari#25]
Attempting to open hidamari returns this error:
`Traceback (most recent call last):
  File "/home/jacopo/.hidamari/hidamari", line 31, in <module>
    import server
  File "/home/jacopo/.hidamari/server.py", line 8, in <module>
    from utils import ConfigUtil
  File "/home/jacopo/.hidamari/utils.py", line 9, in <module>
    gi.require_version("Wnck", "3.0")
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available`

**Comment by Azel04** [comment]
Didn't have libwnck3 installed, my bad.
