### ISSUE TITLE
error when clicking on 'apply'

### ISSUE THREAD

**Issue by apoleon33** [jeffshee/hidamari#29]
when i click on the 'apply' button on the local video section nothing happen, except this error in the terminal:
```
Traceback (most recent call last):
  File "/home/******/.hidamari/gui.py", line 118, in on_local_video_apply
    self.server.video(self.local_video_list[index])
  File "/usr/lib/python3.9/site-packages/pydbus/proxy_method.py", line 72, in __call__
    ret = instance._bus.con.call_sync(
gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:unknown.NameError: no function 'libvlc_new' (36)
```
im on Manjaro with gnome 40.5

**Comment by apoleon33** [comment]
didnt had vlc installed my bad sorry
