### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Gamferno** [jeffshee/hidamari#50]
Completed all the installation steps but got this output as issue

```
Config JSON:
{'audio_volume': 50,
 'data_source': None,
 'is_detect_maximized': True,
 'is_mute': False,
 'is_static_wallpaper': True,
 'mode': None,
 'static_wallpaper_blur_radius': 5,
 'version': 2}
Mode: Null
Monitor: width 1366 height 1366
WindowHandler: {'is_any_maximized': False, 'is_any_fullscreen': True}
Traceback (most recent call last):
  File "/home/om/bin/hidamari", line 33, in <module>
    server.run()
  File "/home/om/.hidamari/server.py", line 172, in run
    hidamari.dbus_published_callback()
  File "/home/om/.hidamari/server.py", line 50, in null
    self.player = NullPlayer(self.config)
  File "/home/om/.hidamari/null_player.py", line 15, in __init__
    self.menu = self._build_context_menu()
  File "/home/om/.hidamari/base_player.py", line 83, in _build_context_menu
    if 'gnome' in os.environ['XDG_CURRENT_DESKTOP'].lower():
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_CURRENT_DESKTOP'
```

**Comment by jeffshee** [comment]
Hi @Gamferno, 
it seems like a distro/DE-specific issue. What distro and DE are you using?
Please check the output of `echo $XDG_SESSION_TYPE` too.

**Comment by jeffshee** [comment]
Closed as the new release is out. Feel free to reopen if the issue still remains.

**Comment by AZMCode** [comment]
I can confirm I get this bug when using the `sway` window manager.
The value of this environment variable is unset, and the value of `XDG_SESSION_TYPE` is `wayland`

**Comment by AZMCode** [comment]
The program seems to not be able to handle if this variable is unset

**Comment by AZMCode** [comment]
```
Traceback (most recent call last):
  File "/app/bin/hidamari", line 44, in <module>
    sys.exit(main.main(VERSION, pkgdatadir, localedir))
  File "/app/share/hidamari/hidamari/__main__.py", line 41, in main
    sys_info.append(f"is_gnome = {is_gnome()}")
  File "/app/share/hidamari/hidamari/utils.py", line 27, in is_gnome
    return "gnome" in os.environ.get("XDG_CURRENT_DESKTOP").lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by AZMCode** [comment]
Created a pull request that fixes the issue
