### ISSUE TITLE
AssertionError on Qtile

### ISSUE THREAD

**Issue by ashroyxi** [jeffshee/hidamari#63]
```
AssertionError
INFO:Hidamari:[GUI] Local Video: /home/ashroy/Videos/Hidamari/beach.mp4
INFO:Hidamari:[Mode] MODE_VIDEO
Gtk-Message: 15:30:06.489: Failed to load module "xapp-gtk3-module"
Gtk-Message: 15:30:06.489: Failed to load module "canberra-gtk-module"
INFO:Hidamari:[GUI] Local Video: /home/ashroy/Videos/Hidamari/beach.mp4
INFO:Hidamari:[Mode] MODE_VIDEO
Gtk-Message: 15:30:06.733: Failed to load module "xapp-gtk3-module"
Gtk-Message: 15:30:06.733: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/app/share/hidamari/hidamari/player/video_player.py", line 240, in do_activate
    super().do_activate()
  File "/app/share/hidamari/hidamari/player/base_player.py", line 106, in do_activate
    gnome_desktop_icon_workaround()
  File "/app/share/hidamari/hidamari/utils.py", line 134, in gnome_desktop_icon_workaround
    assert is_gnome()
AssertionError
name already exists on the bus
Traceback (most recent call last):
  File "/app/share/hidamari/hidamari/player/video_player.py", line 240, in do_activate
    super().do_activate()
  File "/app/share/hidamari/hidamari/player/base_player.py", line 106, in do_activate
    gnome_desktop_icon_workaround()
  File "/app/share/hidamari/hidamari/utils.py", line 134, in gnome_desktop_icon_workaround
    assert is_gnome()
AssertionError
```

**Comment by ashroyxi** [comment]
???

**Comment by jeffshee** [comment]
Hi @ashroyxi, Thanks for reporting.
Fixed in next release. Should be available on Flathub in a few hours =)
