### ISSUE TITLE
Wallpaper nor appearing [Gnome, Wayland, Nvidia Proprietary]

### ISSUE THREAD

**Issue by iFlxy** [jeffshee/hidamari#98]
Hi,

When using your project I noticed an issue on Wayland, my Video Wallpaper does not appear, when a Web Page one is working just fine.
This seems to appear in the console when I'm trying to use a Video Wallpaper:
`libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".`

Output of echo $XDG_SESSION_TYPE:
`[iflxy@iflxypc ~]$ echo $XDG_SESSION_TYPE 
wayland`

Full log:
`[iflxy@iflxypc ~]$ hidamari 
INFO:Hidamari:Hidamari v3.2
--- System information ---
is_gnome = True
is_wayland = True
is_nvidia_proprietary = True
is_vdpau_ok = False
is_flatpak = False
--------------------------
INFO:Hidamari:[Args] {'p': 0, 'background': False, 'debug': False, 'reset': False}
DEBUG:Hidamari:[Config] Loaded /home/iflxy/.config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 50,
   'data_source': '/home/iflxy/Videos/Hidamari/eee.avi',
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_detect_maximized': True,
   'is_first_time': False,
   'is_mute': False,
   'is_show_systray': False,
   'is_static_wallpaper': True,
   'mode': 'MODE_VIDEO',
   'static_wallpaper_blur_radius': 1,
   'version': 3}
--------------------------
INFO:Hidamari:[Mode] MODE_VIDEO
INFO:Hidamari:[Server] Started
Proprietary Nvidia driver detected! HW Acceleration is not yet working in Wayland.
DEBUG:Hidamari:[Config] Loaded /home/iflxy/.config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 50,
   'data_source': '/home/iflxy/Videos/Hidamari/eee.avi',
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_detect_maximized': True,
   'is_first_time': False,
   'is_mute': False,
   'is_show_systray': False,
   'is_static_wallpaper': True,
   'mode': 'MODE_VIDEO',
   'static_wallpaper_blur_radius': 1,
   'version': 3}
--------------------------
Exception in thread Thread-4 (get_thumbnail):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/hidamari/hidamari/gui/gui_utils.py", line 48, in get_thumbnail
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(thumbnail, -1, 96)
TypeError: Argument 0 does not allow None as a value
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
INFO:Hidamari:[GUI] Blur radius: 2
DEBUG:Hidamari:[Config] Saved /home/iflxy/.config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 50,
   'data_source': '/home/iflxy/Videos/Hidamari/eee.avi',
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_detect_maximized': True,
   'is_first_time': False,
   'is_mute': False,
   'is_show_systray': False,
   'is_static_wallpaper': True,
   'mode': 'MODE_VIDEO',
   'static_wallpaper_blur_radius': 2,
   'version': 3}
--------------------------
INFO:Hidamari:[GUI] Local Video: /home/iflxy/Videos/Hidamari/eee.avi
INFO:Hidamari:[Mode] MODE_VIDEO
Proprietary Nvidia driver detected! HW Acceleration is not yet working in Wayland.
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): obladzanie.online:443
DEBUG:urllib3.connectionpool:https://obladzanie.online:443 "GET / HTTP/1.1" 200 None
INFO:Hidamari:[GUI] Webpage: https://obladzanie.online
DEBUG:Hidamari:[Config] Saved /home/iflxy/.config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 50,
   'data_source': 'https://obladzanie.online',
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_detect_maximized': True,
   'is_first_time': False,
   'is_mute': False,
   'is_show_systray': False,
   'is_static_wallpaper': True,
   'mode': 'MODE_WEBPAGE',
   'static_wallpaper_blur_radius': 2,
   'version': 3}
--------------------------
INFO:Hidamari:[Mode] MODE_WEBPAGE
Traceback (most recent call last):
  File "/usr/share/hidamari/hidamari/player/web_player.py", line 83, in do_activate
    self.data_source = self.config[CONFIG_KEY_DATA_SOURCE]
  File "/usr/share/hidamari/hidamari/player/web_player.py", line 107, in data_source
    monitor.set_is_mute(True)
AttributeError: 'X11Monitor' object has no attribute 'set_is_mute'`

I'm using GNOME 43 (on Wayland, of course), also sorry for my bad English.

**Comment by iFlxy** [comment]
Also, I'm using 2 monitors.

**Comment by OliverKreitmeyer** [comment]
I'm having a similar issue. I have an nvidia graphics card with propietary drivers, using gnome on fedora 40 with wayland and all I get is a white screen on Web Page mode.

**Comment by anacierdem** [comment]
I'm testing on Fedora silver blue (Bluefin) and I only see white background with this output form Hidamari:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): alteredqualia.com:443
DEBUG:urllib3.connectionpool:https://alteredqualia.com:443 "GET /xg/examples/morphs_composites.html HTTP/11" 200 None
INFO:Hidamari:[GUI] Webpage: https://alteredqualia.com/xg/examples/morphs_composites.html
DEBUG:Hidamari:[Config] Saved /var/home/anacierdem/.var/app/io.github.jeffshee.Hidamari/config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 50,
   'data_source': {  'DP-5': '',
                     'Default': 'https://alteredqualia.com/xg/examples/morphs_composites.html',
                     'HDMI-1': ''},
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_first_time': False,
   'is_mute': False,
   'is_mute_when_maximized': False,
   'is_pause_when_maximized': True,
   'is_show_systray': False,
   'is_static_wallpaper': True,
   'mode': 'MODE_WEBPAGE',
   'static_wallpaper_blur_radius': 5,
   'version': 4}
--------------------------
INFO:Hidamari:[Mode] MODE_WEBPAGE
Gtk-Message: 22:33:05.406: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:33:05.725: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:33:05.725: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:33:05.726: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:33:05.726: Failed to load module "canberra-gtk-module"
Failed to create GBM buffer of size 2560x1440: Invalid argument
Failed to create GBM buffer of size 2560x1080: Invalid argument
```

`canberra-gtk-module` looks like a sound module, so that shouldn't be the real problem. I don't know why buffer creation fails though.
